### ISSUE TITLE
Problème d'installation du site en local

### ISSUE THREAD

**Issue by HannonTN** [laravel-france/website#22]
Bonjour;

Je trouve des problèmes pour installer le site laravel.fr en local.
J'ai téléchargé le fichier .zip puis j'ai lancé la commande "composer update" et du coup l'erreur s'échappe : 

Warning: require(C:\wamp\www\laravelfr\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\laravelfr\bootstrap\autoload.php on line 17

Call Stack:
    0.0010     123960   1. {main}() C:\wamp\www\laravelfr\artisan:0
    0.0010     127392   2. require('C:\wamp\www\laravelfr\bootstrap\autoload.php') C:\wamp\www\laravelfr\artisan:16

Fatal error: require(): Failed opening required 'C:\wamp\www\laravelfr\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\wamp\www\laravelfr\bootstrap\autoload.php on line 17

Call Stack:
    0.0010     123960   1. {main}() C:\wamp\www\laravelfr\artisan:0
    0.0010     127392   2. require('C:\wamp\www\laravelfr\bootstrap\autoload.php') C:\wamp\www\laravelfr\artisan:16

Il sera judicieux d'ajouter une petite intro sur l'installation complète du site y compris les fichiers .md de la documentation laravel 

Merci

**Comment by JulienTant** [comment]
Bonjour Hannon,

J'avoue que je n'ai pas vraiment d'indice n'utilisant pas Windows moi même. Je vais voir comment simplifier le process d'installation du projet, merci pour ton retour.
