### ISSUE TITLE
[Markdown] - Tableaux

### ISSUE THREAD

**Issue by GustoElC** [laravel-france/website#23]
Pendant l'écriture d'un nouveau sujet, la mise en forme d'un tableau est fonctionnel. Par contre quand le sujet est publié, aucune mise en forme sur le topic !

**Comment by JulienTant** [comment]
Merci pour la remonté !

**Comment by JulienTant** [comment]
Problème résolu : http://laravel.fr/t/laravel-france/mises-a-jour-du-site?page=3#message-3907
