### ISSUE TITLE
suivis - titre date et titre texte non synchronisés

### ISSUE THREAD

**Issue by papajoker** [laravel-france/website#24]
version 3.1  
voir tous les sujets suivis, la date est bien celle du dernier mais le début du message est le premier ... ça porte a confusion; pas mieux les si les 2 champs sont pris dans le dernier message ? uniquement dans "suivis"

**Comment by JulienTant** [comment]
Done, voir https://github.com/laravel-france/website/commit/3ab44565344b02459fe0601f58052dd79febbadf#diff-9caaa61201942163add2f99151f09abcR25

Si c'est un sujet que l'on suit avec des nouvelles réponses, on voit la première réponse non lue. Si c'est un sujet sans nouvelle réponse depuis notre dernière visite, alors on voit le dernier message.
